# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage1/projects/alora-share/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage1/projects/alora-share

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage1/projects/alora-share/CMakeFiles /storage1/projects/alora-share//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage1/projects/alora-share/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aloraShare

# Build rule for target.
aloraShare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aloraShare
.PHONY : aloraShare

# fast build rule for target.
aloraShare/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/build
.PHONY : aloraShare/fast

network/base.o: network/base.cpp.o

.PHONY : network/base.o

# target to build an object file
network/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/base.cpp.o
.PHONY : network/base.cpp.o

network/base.i: network/base.cpp.i

.PHONY : network/base.i

# target to preprocess a source file
network/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/base.cpp.i
.PHONY : network/base.cpp.i

network/base.s: network/base.cpp.s

.PHONY : network/base.s

# target to generate assembly for a file
network/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/base.cpp.s
.PHONY : network/base.cpp.s

network/main.o: network/main.cpp.o

.PHONY : network/main.o

# target to build an object file
network/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/main.cpp.o
.PHONY : network/main.cpp.o

network/main.i: network/main.cpp.i

.PHONY : network/main.i

# target to preprocess a source file
network/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/main.cpp.i
.PHONY : network/main.cpp.i

network/main.s: network/main.cpp.s

.PHONY : network/main.s

# target to generate assembly for a file
network/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/main.cpp.s
.PHONY : network/main.cpp.s

network/tcp.o: network/tcp.cpp.o

.PHONY : network/tcp.o

# target to build an object file
network/tcp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/tcp.cpp.o
.PHONY : network/tcp.cpp.o

network/tcp.i: network/tcp.cpp.i

.PHONY : network/tcp.i

# target to preprocess a source file
network/tcp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/tcp.cpp.i
.PHONY : network/tcp.cpp.i

network/tcp.s: network/tcp.cpp.s

.PHONY : network/tcp.s

# target to generate assembly for a file
network/tcp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/tcp.cpp.s
.PHONY : network/tcp.cpp.s

network/udp.o: network/udp.cpp.o

.PHONY : network/udp.o

# target to build an object file
network/udp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/udp.cpp.o
.PHONY : network/udp.cpp.o

network/udp.i: network/udp.cpp.i

.PHONY : network/udp.i

# target to preprocess a source file
network/udp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/udp.cpp.i
.PHONY : network/udp.cpp.i

network/udp.s: network/udp.cpp.s

.PHONY : network/udp.s

# target to generate assembly for a file
network/udp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aloraShare.dir/build.make CMakeFiles/aloraShare.dir/network/udp.cpp.s
.PHONY : network/udp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aloraShare"
	@echo "... network/base.o"
	@echo "... network/base.i"
	@echo "... network/base.s"
	@echo "... network/main.o"
	@echo "... network/main.i"
	@echo "... network/main.s"
	@echo "... network/tcp.o"
	@echo "... network/tcp.i"
	@echo "... network/tcp.s"
	@echo "... network/udp.o"
	@echo "... network/udp.i"
	@echo "... network/udp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

